### PR TITLE
Add separator and hash capabilities

### PR DESCRIPTION
**Pull request by SetiZ**
- Added `separator` option so we can choose something else than `.`
- Manage the presence of hash in the filename: suffix gets placed just in front of it.

### CODE REVIEW

**Comment by mistakster** [comment]
Hey! Thank you for the PR. I will check it later today.

**Comment by mistakster** [comment]
Sorry, I declined your changes because they break backward compatibility with the existing configurations.

**Comment by SetiZ** [comment]
Oh yes, the hash part. I'll try to fix it

**Comment by mistakster** [comment]
Hi!

I think I have already fixed this. https://github.com/mistakster/postcss-pipeline-webpack-plugin/blob/0f3f17c9fa78d16f8acd314d2fb3a6525771c658/test/file-names.js#L102

Please, try `v5.1.0` with custom `transformName` function in your project.

**Comment by SetiZ** [comment]
I just saw that yes! Nice work!

**Comment by mistakster** [comment]
Thanks! :-)

**Comment by SetiZ** [comment]
is there a way to update the engine?
`{"node":">=6","npm":"^3.0.0"}`

**Comment by mistakster** [comment]
Which versions of node.js and npm do you use? Do you see any error while installing the module? It seems I need to update only "npm" version here.

**Comment by SetiZ** [comment]
yeah only npm version. or at least a `>=x`
I use node: 10.x, npm 6.x

**Pull request merged**
